version: 0.2
phases:
  install:
    runtime-versions:
      golang: 1.12
  build:
    commands:
      - export GO111MODULE=on && go test github.com/aws/aws-secretsmanager-caching-go/secretcache -v
      - export GO111MODULE=on && go test github.com/aws/aws-secretsmanager-caching-go/scintegtests -v
